name: backend-nest-local

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
