# services:
#   postgres:
#     image: postgres:alpine
#     restart: always
#     ports:
#       - '5432:5432'
#     environment:
#       POSTGRES_DB: postgres
#       POSTGRES_USER: local
#       POSTGRES_PASSWORD: local
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   nestjs:
#     build: ./
#     restart: always
#     ports:
#       - '3000:3000'
#     depends_on:
#       - postgres
#     volumes:
#       - .:/app
#       - /app/node_modules
#     env_file:
#       - ./.env.local

# volumes:
#   pgdata:
#   node_modules:
