services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

  nestjs:
    build: ./
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - ./.env

volumes:
  pgdata:
