name: Deploy to DEV-EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          script: |
            sudo service docker start
            cd /home/ec2-user/backend-nest

            # Baixar o script de exportação de variáveis
            curl -o export-dev-envs.sh https://raw.githubusercontent.com/your-repo/backend-nest/dev/export-dev-envs.sh
            chmod +x export-dev-envs.sh

            # Executar o script de exportação de variáveis
            source ./export-dev-envs.sh

            git pull origin dev
            docker-compose -f docker-compose.dev.yaml down
            docker-compose -f docker-compose.dev.yaml up -d --build
