name: Deploy to DEV-EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEV_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          script: |
            sudo service docker start
            cd /home/ec2-user/backend-nest
            aws ssm get-parameters-by-path --path /dev --with-decryption --region your-region --query "Parameters[*].[Name,Value]" --output text | awk '{print $1 "=" $2}' > .env
            git pull origin dev
            docker-compose -f docker-compose.dev.yaml down
            docker-compose -f docker-compose.dev.yaml up -d --build
